obstacle_range: 3.0
raytrace_range: 3.5

#footprint: [[0.0685, 0.0685], [-0.0685, 0.0685], [-0.0685, -0.0685], [0.0685, -0.0685]]
footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
#robot_radius: 0.105

inflation_radius: 1.0
cost_scaling_factor: 3.0

observation_sources: laser_scan_sensor 
# point_cloud_sensor

laser_scan_sensor: {sensor_frame: link_LIDAR, data_type: LaserScan, topic: scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
