local_costmap:
  global_frame: odom
  robot_base_frame: link_0

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  static_map: true
  rolling_window: true
  width: 15.0
  height: 15.0
  resolution: 0.05
